version: '3.8'
services:
  db:
    image: postgres:latest
    ports:
      - ${DB_PORT}:${DB_PORT}
    command: -p ${DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    restart: on-failure
    volumes:
      - ${DB_PATH}:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} -p ${DB_PORT} -h localhost" ]
      interval: 10s
      timeout: 3s
      retries: 10
  product-tracing-aggregator:
    image: cardanofoundation/cf-product-tracing-aggregator:${BOLNISI_AGGREGATOR_DOCKER_IMAGE_TAG}
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
        DB_DRIVER: ${DB_DRIVER}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_SCHEMA: ${DB_SCHEMA}
        CARDANO_NODE_HOST: ${CARDANO_NODE_HOST}
        CARDANO_NODE_PORT: ${CARDANO_NODE_PORT}
        PROTOCOL_MAGIC: ${PROTOCOL_MAGIC}
        INDEXER_START_SLOT: ${INDEXER_START_SLOT}
        INDEXER_START_HASH: ${INDEXER_START_HASH}
        OFFCHAIN_RESOLVER_URL: ${OFFCHAIN_RESOLVER_URL}
        PUBLIC_KEY_URL: ${PUBLIC_KEY_URL}
        PUBLIC_KEY_REPLACER: ${PUBLIC_KEY_REPLACER}
